#!/usr/bin/env bash
#
# use --no-verify flag to avoid this script
echo "Running Grunt lint..."

grunt lint
RESULT1=$?

[ $RESULT1 -ne 0 ] && exit 1

echo "Running Grunt test..."

grunt test
RESULT2=$?

[ $RESULT2 -ne 0 ] && exit 1

echo "Running Grunt test e2e..."

grunt test:e2e
RESULT3=$?

[ $RESULT3 -ne 0 ] && exit 1
exit 0
